### ISSUE TITLE
ncnn::Layer  

### ISSUE THREAD

**Issue by huyunlei** [Qengineering/YoloV5-ncnn-Raspberry-Pi-4#1]
Dear author, I can run yolov3, but I can't run yolov5. The error is: ncnn:: layer is not defined. It seems that there is no definition. Can you give me some advice.
![image](https://user-images.githubusercontent.com/57059809/114729307-6fa74d80-9d72-11eb-94a3-6d0b62968f90.png)

**Comment by Qengineering** [comment]
Dear @huyunlei,

YoloV5 has an user defined layer, which is not the case in YoloV3 or YoloV4.
line 463 in YoloV5.cpp
```
yolov5.register_custom_layer("YoloV5Focus", YoloV5Focus_layer_creator);
```
My advise, make absolutely sure you have the latest ncnn version on your machine. (GitHub version 20210322),
Make also sure you use the same flags during compilation and linking as in the YoloV5.cbp file, even if you not using code::blocks.

**Comment by Qengineering** [comment]
Just updated the Code::Blocks project file for the new ncnn version.

**Comment by huyunlei** [comment]
@Qengineering 作者您好，emm，您可以看一下这个 https://github.com/Tencent/ncnn/issues/1376 用这个也可以解决。
Hello author, emm, you can take a look at this https://github.com/Tencent/ncnn/issues/1376 It can also be solved with this.

**Comment by huyunlei** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发来的邮件已经收到，我会尽快给您回复。
